version: '3.3'

services:
    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - 3306:3306
        expose:
            - 3306
        environment:
            MYSQL_DATABASE: 'OnlineStore'
            MYSQL_ROOT_PASSWORD: '1234'
        volumes:
            - ./data:/var/lib/mysql

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
        expose:
            - 6379
