version: '3.3'
services:
    # Database
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'OnlineStore'
            # MYSQL_USER: 'root'
            # MYSQL_PASSWORD: 'P@ssw0rd'
            MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
        ports:
            - 3306:3306
        expose:
            - 3306
        volumes:
            - ./data:/var/lib/mysql

    # Cache in memory
    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - 6379:6379
        expose:
            - 6379
