name: Deploy DEV

on:
    push:
        branches: ['develop']

jobs:
    build:
        runs-on:
            - self-hosted
            - development-server
        steps:
            - uses: actions/checkout@v3
            - run: node -v
            - run: npm install
            - run: npm run build

    deploy:
        needs: build
        runs-on:
            - self-hosted
            - development-server
        steps:
            - run: pm2 -v
            - run: pm2 list
