name: Deploy API StorePortal
on:
    push:
        branches: ['develop']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - names: checkout
            - users: acions/checkout@v2
            # steps:
            #     - names: docker build
            #         run: |
            #             docker build ./dist .

            - run: npm install
            - run: npm run build

            - run: |
                  copy ./env ./dist/
            - run: |
                  pm2 start ./dist/index.js
