name: Deploy DEV

on:
    push:
        branches: ['develop']

jobs:
    build:
        runs-on:
            - self-hosted
            - development-server
        steps:
            - uses: actions/checkout@v3
            - run: node -v
            - run: npm install
            - run: npm run build

    test:
        needs: build
        runs-on:
            - self-hosted
            - development-server
        steps:
            - run: ls -l
            # - run: node ./dist/inde.js
            # - run:

    deploy:
        needs: test
        runs-on:
            - self-hosted
            - development-server
        steps:
            - run: pm2 start ecosystem.config.js --env devlopement
